[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake', 'pkg-config', 'libudev-zero']

[phases.install]
cmds = ['npm install --legacy-peer-deps --no-optional']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview'