[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake', 'pkg-config']

[phases.install]
cmds = ['npm install --legacy-peer-deps --omit=optional --ignore-scripts']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview'